name: Auto Generate README

on:
  push:
    paths:
      - 'metadata/semantic_index.json'
      - 'scripts/generate_readme.py'
  workflow_dispatch:

permissions:
  contents: write  # コミット＆プッシュに必要

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # GITHUB_TOKEN を利用

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # ここに README 生成に必要なライブラリを追加
          pip install -r requirements.txt

      - name: Run README Generator
        run: |
          python scripts/generate_readme.py

      - name: Move to main README
        run: |
          mv README.generated.md README.md

      - name: Commit and push README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "Auto-update README from semantic_index.json"
          git push