# .github/workflows/test.yml

name: Run Pytest

on:
  push:
    paths:
      - 'models/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
      - 'scripts/generate_readme.py'
      - 'metadata/semantic_index.json'
      - 'README.generated.md'
      - 'README.md'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ← ここで README を自動再生成
      - name: Generate README
        run: |
          python scripts/generate_readme.py
          mv README.generated.md README.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install package and test dependencies
        run: |
          python -m pip install --upgrade pip
          # プロジェクト本体をインストール
          pip install -e .
          # テストランナーと Parquet サポートを追加インストール
          pip install pytest pyarrow

      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          pytest tests/ \
            --maxfail=3 \
            --disable-warnings \
            -q