name: Run Pytest

on:
  push:
    paths:
      - 'models/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install package and test dependencies
        run: |
          python -m pip install --upgrade pip
          # setuptools の extras_require で dev 用パッケージをまとめる
          pip install -e ".[dev]"

      - name: Run tests
        run: |
          pytest tests/ \
            --maxfail=3 \
            --disable-warnings \
            -q