name: Run Pytest

on:
  push:
    paths:
      - 'src/**'
      - 'models/**'
      - 'tests/**'
      - 'examples/**'
      - '.github/workflows/test.yml'
      - 'scripts/generate_readme.py'
      - 'metadata/semantic_index.json'
      - 'README.generated.md'
      - 'README.md'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate README
        run: |
          python scripts/generate_readme.py
          mv README.generated.md README.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install package and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pandas numpy tqdm transformers
          python -c "import pandas, numpy, tqdm, transformers"
pip install pytest pyarrow

      - name: Run PoR detector on dummy data (CSV)
        run: |
          python -m ugher_exp.por_detector \
            --input examples/dummy_dialog.csv \
            --output examples/dummy_dialog_por_result.csv

      - name: Verify PoR detector output (CSV)
        run: |
          test -f examples/dummy_dialog_por_result.csv

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest tests/ \
            --maxfail=3 \
            --disable-warnings \
            -q