name: Run Pytest

on:
  push:
    # テスト対象のファイル・フォルダを限定
    paths:
      - 'unconscious-gravity/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # このディレクトリを「作業ルート」として扱う
    defaults:
      run:
        working-directory: ./unconscious-gravity

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests with pytest
        # models/ や tests/ をモジュールとして認識させる
        env:
          PYTHONPATH: ${{ github.workspace }}/unconscious-gravity
        run: |
          pytest tests/ --maxfail=3 --disable-warnings -q